steps:
  - name: 抓取热搜
    skill: toolbox_execute
    params:
      action: script
      language: python
      script: |
        import requests
        import json
        from datetime import datetime
        
        url = "https://top.baidu.com/api/board?platform=wise&tab=realtime"
        headers = {"User-Agent": "Mozilla/5.0"}
        
        try:
            resp = requests.get(url, headers=headers, timeout=10)
            data = resp.json()
            cards = data.get("data", {}).get("cards", [])
            
            hotsearch_list = []
            if cards:
                content = cards[0].get("content", [])
                if content and isinstance(content[0], dict) and "content" in content[0]:
                    items = content[0].get("content", [])
                else:
                    items = content
                
                for i, item in enumerate(items[:20], 1):
                    hotsearch_list.append({
                        "rank": i,
                        "title": item.get("word", ""),
                        "url": item.get("url", "")
                    })
            
            result = {
                "status": "success",
                "update_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "total_count": len(hotsearch_list),
                "hotsearch_list": hotsearch_list,
                "summary": f"获取到 {len(hotsearch_list)} 条百度实时热搜"
            }
            print(json.dumps(result, ensure_ascii=False))
        except Exception as e:
            print(json.dumps({"status": "error", "message": str(e)}, ensure_ascii=False))